name: Terraform Network Dev

on:
  pull_request:
    paths:
      - "infra/**"
      - ".github/workflows/terraform-network-dev.yml"
  push:
    branches:
      - main
    paths:
      - "infra/**"
      - ".github/workflows/terraform-network-dev.yml"
  workflow_dispatch:
    inputs:
      run_apply:
        description: "Run terraform apply with reviewed plan artifact"
        required: true
        default: "true"
        type: choice
        options:
          - "false"
          - "true"

permissions:
  contents: read
  id-token: write
  issues: write

jobs:
  call:
    uses: ./.github/workflows/terraform-base.yml
    with:
      tf_working_dir: infra/stacks/network/dev
      tf_vars_file: ../../../env/dev/network-dev.tfvars
      environment_name: dev
      auto_apply_main: false
      run_apply: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_apply == 'true' }}
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}